### ISSUE TITLE
Review Tab Panel

### ISSUE THREAD

**Issue by surma** [GoogleChrome/dash-elements#13]
My tab panel pretty much made it to the repo without any actual reviews. I’d appreciate if either of you would give it a look to make sure I’m not doing random crap.

**Comment by robdodson** [comment]
## Big Stuff:

The element isn't currently using ARIA correctly. See the [Roles, States, and Properties section of the ARIA Authoring Practices Guide](https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-16). Also, make sure to do a pass with something like VoiceOver to see if it's announcing things properly. Usually VoiceOver will announce the role which can be an indicator if things are working as expected.

- The `<dash-tab-panel>` should self apply `role=tablist`. It may be better to rename this outter element to `<dash-tabs>` or `<dash-tablist>` to match its ARIA role.
- Element and demo use `aria-role=` but it should be `role=`
- Currently you say `aria-controls="tab1"` but it could be better expressed as `aria-controls="panel1" since a `tab` is really thought of as controlling a `tabpanel`.
- Each element with role `tabpanel` should have an `aria-labelledby` referring to its associated `tab` element.

Compare the difference in VoiceOver output (shown in black box at the bottom) when correct ARIA is used

**Before**:

![image](https://cloud.githubusercontent.com/assets/1066253/22752876/ede1507a-edee-11e6-8779-34ba03c06d84.png)


**After**:

![image](https://cloud.githubusercontent.com/assets/1066253/22752851/d5905b10-edee-11e6-8711-2ed67a85a4d5.png)


## Smaller Stuff:

- https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L7 You don't need `aria-hidden` if something is `display: none` because `display: none` removes it from the a11y tree. Also you might reword this to say something like "inactive panels are hidden with display none" since the next section talks about selection. Otherwise it may not be clear that the two concepts are related.
- This opening section initially confused me https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L14-L21. I wasn't sure which element was going to be a tab or a panel or a tabpanel. I had to look at the demo to figure it out.
- I would remove this comment https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L30-L31. It's not really for accessibility, it's just for general usability that the element must handle the keyboard and mouse.
- You don't need to bind to this https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L32-L33. `this` will always refer to the `TabPanel` instance because of how you've added the listener. Also you may want to add those listeners in `connectedCallback` so you can remove them in `disconnectedCallback`.
- https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L44-L45 should be `role=`
- Style nit: https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L47 I usually do `if (!tabs.length)`. @notwaldorf do you prefer one approach to the other?
- https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L62 Maybe rename `e` to `element`? or something more descriptive
- https://github.com/GoogleChrome/dash-elements/blob/master/elements/dash-tab-panel/dash-tab-panel.js#L73-L74 should be `role=`

## Personal Opinion Stuff:

I'd be curious to see if it's possible to build the entire structure out of custom elements, something like:

```
<dash-tabs>
  <dash-tab></dash-tab>
  <dash-tabpanel></dash-tabpanel>
</dash-tabs>
```

You could do some (possibly weird 😄 ) things for PE like give the tab a `role=heading` explicitly in markup, but then that gets swapped out with `role=tab` when the element upgrades. The more I think about this the more I kinda like this idea. It seems to dovetail well into the PE use case because it's saying "if JS doesn't load, this thing's role is something more basic, but if js _does_ load, it's new role is more advanced". Most importantly it gives the user a signal that the thing is now keyboard interactive.
