### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/dash-elements#14]
I'd like to show two different radio groups, 1 using roving tabindex and 1 using aria-activedescendant. What do you all think would be the best way to handle variations of a pattern?

**Comment by surma** [comment]
Interesting! From the top of my head I see the following options:

* Completely separate elements, feels a little weird tho
* Some sort of comment syntax to denote alternatives and you can switch between them in the UI. This kinda assumes that the changes needed for the different alternatives are very local.
* Using the alternatives in different elements and linking to each other in the comments (something like “Instead of using roving tabindex you could be using activedescendant. See `<dash-checkbox>` for an example). I like this version the best, as it minimizes duplication and encourages more reading, but not sure if it is sufficient for what you are planning.

**Comment by robdodson** [comment]
I think we can go with option 3 to make things easy
